# Generated by Django 5.2.17 on 2026-08-06 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('total_count', models.IntegerField()),
                ('available_count', models.IntegerField()),
                ('loaned_count', models.IntegerField()),
                ('maintenance_status', models.CharField(default='Good', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='MedicineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('stock_quantity', models.IntegerField()),
                ('unit', models.CharField(max_length=50)),
                ('reorder_level', models.IntegerField()),
                ('expiry_date', models.DateField()),
                ('batch_number', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='organizations.organization')),
            ],
        ),
    ]
