# Generated by Django 5.2.17 on 2026-08-25 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentitem',
            name='maintenance_status',
            field=models.CharField(choices=[('Available', 'Available'), ('Reserved', 'Reserved'), ('Issued', 'Issued'), ('Under Maintenance', 'Under Maintenance'), ('Returned', 'Returned')], default='Available', max_length=50),
        ),
        migrations.CreateModel(
            name='MedicineTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('RECEIVED', 'Stock Received'), ('ISSUED_TO_PATIENT', 'Issued to Patient'), ('RETURNED', 'Stock Returned'), ('EXPIRED_DISCARD', 'Expired & Discarded')], max_length=50)),
                ('quantity', models.IntegerField()),
                ('recorded_by', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.medicineitem')),
            ],
        ),
    ]
