import '../models/network_models.dart';

class NetworkDatabaseService {
  static List<SpecialtyModel> getInitialSpecialties() {
    return const [
      SpecialtyModel(id: 'SPEC-01', name: 'Cardiology', iconName: 'favorite', description: 'Heart & Vascular Care'),
      SpecialtyModel(id: 'SPEC-02', name: 'Palliative & Pain Medicine', iconName: 'volunteer_activism', description: 'Supportive & Hospice Care'),
      SpecialtyModel(id: 'SPEC-03', name: 'Medical & Surgical Oncology', iconName: 'biotech', description: 'Cancer Care & Chemotherapy'),
      SpecialtyModel(id: 'SPEC-04', name: 'Neurology & Neurosurgery', iconName: 'psychology', description: 'Brain & Spine Care'),
      SpecialtyModel(id: 'SPEC-05', name: 'Orthopedics & Joint Care', iconName: 'accessibility', description: 'Bone, Joint & Trauma Surgery'),
      SpecialtyModel(id: 'SPEC-06', name: 'Pediatrics & Neonatology', iconName: 'child_care', description: 'Child & Infant Healthcare'),
      SpecialtyModel(id: 'SPEC-07', name: 'Nephrology & Dialysis', iconName: 'water_drop', description: 'Kidney Health & Dialysis'),
      SpecialtyModel(id: 'SPEC-08', name: 'Pulmonology', iconName: 'air', description: 'Chest & Respiratory Medicine'),
      SpecialtyModel(id: 'SPEC-09', name: 'General Medicine', iconName: 'health_and_safety', description: 'Adult Primary Care & Fevers'),
      SpecialtyModel(id: 'SPEC-10', name: 'Emergency & Critical Care', iconName: 'emergency', description: '24x7 Emergency & Trauma Care'),
    ];
  }

  static List<DoctorModel> getInitialDoctors() {
    return const [
      DoctorModel(
        id: 'DOC-101',
        name: 'Dr. Suresh Kumar MD',
        qualification: 'MD, DNB (Palliative Medicine), FPCM',
        specialty: 'Palliative & Pain Medicine',
        designation: 'Chief Medical Director & Palliative Specialist',
        organizationId: 'org_kozhikode',
        organizationName: 'Calicut Medical Center & Palliative Institute',
        district: 'Kozhikode',
        experienceYears: 18,
        languages: 'Malayalam, English, Hindi',
        registrationNumber: 'TCMC-24891',
        isRegVerified: true,
        consultationMode: 'In-Person, Video & Home Visit',
        consultationFee: 0.00,
        isCareLinkVerified: true,
        biography: 'Pioneering community palliative care specialist with 18+ years leading pain management and hospice care for bedridden elders across Malabar.',
        schedules: [
          DoctorScheduleModel(
            id: 'SCH-01',
            dayOfWeek: 'Monday',
            startTime: '09:00 AM',
            endTime: '01:00 PM',
            locationRoom: 'OPD Room 101 (Palliative Wing)',
            consultationType: 'Pain & Symptom Management',
          ),
          DoctorScheduleModel(
            id: 'SCH-02',
            dayOfWeek: 'Wednesday',
            startTime: '09:00 AM',
            endTime: '01:00 PM',
            locationRoom: 'OPD Room 101',
            consultationType: 'General Palliative OPD',
          ),
          DoctorScheduleModel(
            id: 'SCH-03',
            dayOfWeek: 'Friday',
            startTime: '02:00 PM',
            endTime: '05:00 PM',
            locationRoom: 'Community Triage Center',
            consultationType: 'Home Care Team Review',
          ),
        ],
      ),
      DoctorModel(
        id: 'DOC-102',
        name: 'Dr. Priya Varma MD',
        qualification: 'MD (Internal Medicine), DM (Medical Oncology)',
        specialty: 'Medical & Surgical Oncology',
        designation: 'Senior Consultant Medical Oncologist',
        organizationId: 'org_kozhikode',
        organizationName: 'Calicut Medical Center & Palliative Institute',
        district: 'Kozhikode',
        experienceYears: 14,
        languages: 'Malayalam, English',
        registrationNumber: 'TCMC-31045',
        isRegVerified: true,
        consultationMode: 'In-Person Hospital OPD',
        consultationFee: 400.00,
        isCareLinkVerified: true,
        biography: 'Senior medical oncologist specializing in solid tumors, targeted chemotherapy, and immunotherapy with compassionate patient navigation.',
        schedules: [
          DoctorScheduleModel(
            id: 'SCH-04',
            dayOfWeek: 'Tuesday',
            startTime: '10:00 AM',
            endTime: '02:00 PM',
            locationRoom: 'Oncology Suite 204',
            consultationType: 'Oncology Specialist OPD',
          ),
          DoctorScheduleModel(
            id: 'SCH-05',
            dayOfWeek: 'Thursday',
            startTime: '10:00 AM',
            endTime: '02:00 PM',
            locationRoom: 'Oncology Suite 204',
            consultationType: 'Chemotherapy Protocol Review',
          ),
          DoctorScheduleModel(
            id: 'SCH-06',
            dayOfWeek: 'Saturday',
            startTime: '10:00 AM',
            endTime: '01:00 PM',
            locationRoom: 'Oncology Suite 204',
            consultationType: 'New Patient Triage',
          ),
        ],
      ),
      DoctorModel(
        id: 'DOC-103',
        name: 'Dr. Anil Kumar DM',
        qualification: 'MD, DM (Cardiology), FACC',
        specialty: 'Cardiology',
        designation: 'Head of Interventional Cardiology',
        organizationId: 'org_kozhikode',
        organizationName: 'Calicut Medical Center & Palliative Institute',
        district: 'Kozhikode',
        experienceYears: 16,
        languages: 'Malayalam, English, Tamil',
        registrationNumber: 'TCMC-19820',
        isRegVerified: true,
        consultationMode: 'In-Person Hospital OPD',
        consultationFee: 500.00,
        isCareLinkVerified: true,
        biography: 'Interventional cardiologist performing primary angioplasty, heart failure management, and preventive cardiovascular triage.',
        schedules: [
          DoctorScheduleModel(
            id: 'SCH-07',
            dayOfWeek: 'Monday',
            startTime: '04:00 PM',
            endTime: '07:00 PM',
            locationRoom: 'Cardiology Lab C-1',
            consultationType: 'Cardiac Consultation',
          ),
          DoctorScheduleModel(
            id: 'SCH-08',
            dayOfWeek: 'Wednesday',
            startTime: '04:00 PM',
            endTime: '07:00 PM',
            locationRoom: 'Cardiology Lab C-1',
            consultationType: 'Post-Angioplasty Follow-up',
          ),
          DoctorScheduleModel(
            id: 'SCH-09',
            dayOfWeek: 'Friday',
            startTime: '04:00 PM',
            endTime: '07:00 PM',
            locationRoom: 'Cardiology Lab C-1',
            consultationType: 'Echo & Heart Failure Review',
          ),
        ],
      ),
      DoctorModel(
        id: 'DOC-104',
        name: 'Dr. Sunitha Menon MD',
        qualification: 'MBBS, MD (Pediatrics)',
        specialty: 'Pediatrics & Neonatology',
        designation: 'Consultant Pediatrician',
        organizationId: 'org_ernakulam',
        organizationName: 'Ernakulam Care Palliative Trust & Specialty Clinic',
        district: 'Ernakulam',
        experienceYears: 11,
        languages: 'Malayalam, English',
        registrationNumber: 'TCMC-40192',
        isRegVerified: true,
        consultationMode: 'In-Person & Telemedicine Video',
        consultationFee: 300.00,
        isCareLinkVerified: true,
        biography: 'Experienced pediatrician focusing on pediatric palliative comfort, growth disorders, and routine newborn development.',
        schedules: [
          DoctorScheduleModel(
            id: 'SCH-10',
            dayOfWeek: 'Monday',
            startTime: '09:30 AM',
            endTime: '01:30 PM',
            locationRoom: 'Child Care Suite 4',
            consultationType: 'Pediatric General OPD',
          ),
          DoctorScheduleModel(
            id: 'SCH-11',
            dayOfWeek: 'Wednesday',
            startTime: '09:30 AM',
            endTime: '01:30 PM',
            locationRoom: 'Child Care Suite 4',
            consultationType: 'Immunization & Triage',
          ),
          DoctorScheduleModel(
            id: 'SCH-12',
            dayOfWeek: 'Saturday',
            startTime: '10:00 AM',
            endTime: '01:00 PM',
            locationRoom: 'Child Care Suite 4',
            consultationType: 'Weekend Child Clinic',
          ),
        ],
      ),
    ];
  }

  static List<HealthcareProfileModel> getInitialHealthcareDirectory() {
    final docs = getInitialDoctors();
    return [
      HealthcareProfileModel(
        id: 'HOSP-01',
        organizationId: 'org_kozhikode',
        name: 'Calicut Medical Center & Palliative Institute',
        organizationType: 'Multispecialty Hospital',
        ownershipType: 'Charitable Trust',
        verificationStatus: 'VERIFIED',
        isCareLinkVerified: true,
        district: 'Kozhikode',
        address: 'Mavoor Road Junction, Medical College PO, Kozhikode, Kerala 673008',
        pincode: '673008',
        latitude: 11.2721,
        longitude: 75.8342,
        phone: '+91 495 272 1000',
        emergencyPhone: '+91 495 272 1999',
        is24x7Emergency: true,
        ambulanceAvailable: true,
        totalBeds: 450,
        icuBeds: 45,
        description: 'NABH-accredited 450-bed hospital with 24x7 trauma care, dedicated 50-bed palliative oncology wing, and 12 community home care mobile vans.',
        profileCompletenessScore: 96,
        lastVerifiedDate: '31 Aug 2026',
        specialties: const [
          'Cardiology',
          'Palliative & Pain Medicine',
          'Medical & Surgical Oncology',
          'Neurology & Neurosurgery',
          'Orthopedics & Joint Care',
          'Emergency & Critical Care',
        ],
        services: const [
          '24x7 Emergency & Trauma Care',
          'Intensive Care Unit (ICU / CCU)',
          'Dialysis Unit',
          'Blood Bank & Component Center',
          '24x7 In-House Pharmacy',
          'Diagnostic MRI & CT Imaging',
          'Palliative Home Care Fleet',
        ],
        facilities: const [
          'Wheelchair & Stretcher Accessible',
          'Centralized Medical Oxygen Supply',
          'Jan Aushadhi Free Medicine Counter',
          '24x7 Power Backup Generator',
          'Ample Visitor Parking',
        ],
        doctors: [docs[0], docs[1], docs[2]],
      ),
      HealthcareProfileModel(
        id: 'HOSP-02',
        organizationId: 'org_ernakulam',
        name: 'Ernakulam Care Palliative Trust & Specialty Clinic',
        organizationType: 'Palliative Care Center',
        ownershipType: 'Charitable Trust',
        verificationStatus: 'VERIFIED',
        isCareLinkVerified: true,
        district: 'Ernakulam',
        address: 'Near Changampuzha Park, Edappally, Kochi, Kerala 682024',
        pincode: '682024',
        latitude: 10.0261,
        longitude: 76.3125,
        phone: '+91 484 234 5678',
        emergencyPhone: '+91 484 234 5999',
        is24x7Emergency: true,
        ambulanceAvailable: true,
        totalBeds: 60,
        icuBeds: 8,
        description: 'Community-led palliative care foundation providing zero-cost home care, pain relief medications, and free oxygen concentrator loans.',
        profileCompletenessScore: 92,
        lastVerifiedDate: '30 Aug 2026',
        specialties: const [
          'Palliative & Pain Medicine',
          'Pediatrics & Neonatology',
          'General Medicine',
          'Pulmonology',
        ],
        services: const [
          'Palliative Home Care Fleet',
          'Free Oxygen Concentrator Depot',
          'Dialysis Support Wing',
          'Wound Care & Dressing Clinic',
          'Ambulance Services',
        ],
        facilities: const [
          'Wheelchair Accessible',
          'Free Medicine Counter',
          'Oxygen Bank',
          'Caregiver Rest Area',
        ],
        doctors: [docs[3]],
      ),
      HealthcareProfileModel(
        id: 'HOSP-03',
        organizationId: 'org_wayanad',
        name: 'Wayanad Tribal Health Mission & Hospital',
        organizationType: 'General Hospital',
        ownershipType: 'Mission Hospital',
        verificationStatus: 'VERIFIED',
        isCareLinkVerified: true,
        district: 'Wayanad',
        address: 'Main Highway, Kalpetta, Wayanad, Kerala 673121',
        pincode: '673121',
        latitude: 11.6050,
        longitude: 76.0830,
        phone: '+91 493 620 4400',
        emergencyPhone: '+91 493 620 4911',
        is24x7Emergency: true,
        ambulanceAvailable: true,
        totalBeds: 120,
        icuBeds: 12,
        description: 'Dedicated highland healthcare center serving tribal colonies and rural families with mobile healthcare clinics and emergency triage.',
        profileCompletenessScore: 88,
        lastVerifiedDate: '28 Aug 2026',
        specialties: const [
          'General Medicine',
          'Pediatrics & Neonatology',
          'Emergency & Critical Care',
          'Orthopedics & Joint Care',
        ],
        services: const [
          '24x7 Emergency Care',
          'Dialysis Unit',
          'Highland 4x4 Ambulance',
          'Blood Storage Center',
        ],
        facilities: const [
          'Wheelchair Accessible',
          'Medical Oxygen Support',
          'Visitor Canteen',
        ],
        doctors: const [],
      ),
      HealthcareProfileModel(
        id: 'HOSP-04',
        organizationId: 'org_tvm',
        name: 'Thiruvananthapuram Institute of Palliative Sciences',
        organizationType: 'Multispecialty Hospital',
        ownershipType: 'Trust / Non-Profit',
        verificationStatus: 'VERIFIED',
        isCareLinkVerified: true,
        district: 'Thiruvananthapuram',
        address: 'Medical College Campus, Thiruvananthapuram, Kerala 695011',
        pincode: '695011',
        latitude: 8.5241,
        longitude: 76.9366,
        phone: '+91 471 244 8800',
        emergencyPhone: '+91 471 244 8899',
        is24x7Emergency: true,
        ambulanceAvailable: true,
        totalBeds: 200,
        icuBeds: 25,
        description: 'WHO demonstration hospice center for chronic pain management, cancer comfort, and home palliative care training.',
        profileCompletenessScore: 94,
        lastVerifiedDate: '29 Aug 2026',
        specialties: const [
          'Palliative & Pain Medicine',
          'Medical & Surgical Oncology',
          'Pulmonology',
          'Nephrology & Dialysis',
        ],
        services: const [
          '24x7 Pain Helpline & Ambulance',
          'Day-Care Chemotherapy',
          'Home Nursing Squad',
          'In-House Pharmacy',
        ],
        facilities: const [
          'Wheelchair Accessible',
          'Central Oxygen Bank',
          'Jan Aushadhi Counter',
        ],
        doctors: const [],
      ),
    ];
  }

  static List<ChangeRequestModel> getInitialChangeRequests() {
    return [
      const ChangeRequestModel(
        id: 'CR-101',
        organizationId: 'org_kozhikode',
        organizationName: 'Calicut Medical Center & Palliative Institute',
        requestedByName: 'Arjun Das (Content Moderator)',
        entityType: 'Doctor Schedule Update',
        changeSummary: 'Update Dr. Anil Kumar Saturday OPD timing from 04:00 PM to 05:00 PM',
        oldData: {'day': 'Saturday', 'time': '04:00 PM - 07:00 PM', 'room': 'Cardiology Lab C-1'},
        newData: {'day': 'Saturday', 'time': '05:00 PM - 08:00 PM', 'room': 'Cardiology Lab C-1'},
        reason: 'Adjusted for elective Cath Lab coronary angiogram scheduling.',
        status: 'PENDING',
        createdAt: '31 Aug 2026',
      ),
      const ChangeRequestModel(
        id: 'CR-102',
        organizationId: 'org_kozhikode',
        organizationName: 'Calicut Medical Center & Palliative Institute',
        requestedByName: 'Sr. Anitha Kumari (Staff)',
        entityType: 'Emergency Contact Update',
        changeSummary: 'Add dedicated 24x7 Trauma Care WhatsApp Helpline',
        oldData: {'emergency_phone': '+91 495 272 1999'},
        newData: {'emergency_phone': '+91 495 272 1999', 'whatsapp_triage': '+91 94470 11999'},
        reason: 'Community ambulance fast dispatch line upgrade.',
        status: 'PENDING',
        createdAt: '30 Aug 2026',
      ),
    ];
  }

  static List<ClaimOrganizationRequestModel> getInitialClaimRequests() {
    return const [
      ClaimOrganizationRequestModel(
        id: 'CLM-01',
        organizationId: 'org_wayanad',
        organizationName: 'Wayanad Tribal Health Mission & Hospital',
        claimantUsername: 'dr_mathew_director',
        claimantDesignation: 'Medical Superintendent & Trustee',
        officialEmail: 'superintendent@wayanadhealthmission.org',
        officialPhone: '+91 94470 55123',
        proofDocumentUrl: 'https://carelink.kerala.gov.in/docs/trust_deed_wayanad.pdf',
        status: 'PENDING',
      ),
    ];
  }
}
