# Generated by Django 5.2.17 on 2026-08-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('Payment Pending', 'Payment Pending'), ('Paid', 'Paid'), ('Receipt Generated', 'Receipt Generated'), ('Completed', 'Completed')], default='Completed', max_length=50),
        ),
        migrations.AddField(
            model_name='donation',
            name='transaction_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
