# Generated by Django 5.2.17 on 2026-08-28 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_donation_status_donation_transaction_id'),
        ('organizations', '0002_organization_bank_account_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='donor_prayer',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='donation',
            name='fundraiser_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='donation',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donation',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='razorpay_order_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='donation',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='donation',
            name='razorpay_signature',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.CreateModel(
            name='MedicalFundraiser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=200)),
                ('patient_age', models.IntegerField(default=40)),
                ('patient_gender', models.CharField(default='Male', max_length=20)),
                ('blood_group', models.CharField(default='O+', max_length=10)),
                ('district', models.CharField(max_length=100)),
                ('ward', models.CharField(max_length=100)),
                ('hospital_name', models.CharField(max_length=255)),
                ('doctor_name', models.CharField(max_length=200)),
                ('treatment_title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('collected_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('donors_count', models.IntegerField(default=0)),
                ('story', models.TextField()),
                ('medical_estimate_summary', models.TextField(blank=True, default='')),
                ('is_doctor_verified', models.BooleanField(default=True)),
                ('days_remaining', models.IntegerField(default=30)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('patient_family_gratitude_message', models.TextField(blank=True, default='')),
                ('use_org_qr', models.BooleanField(default=True)),
                ('custom_upi_id', models.CharField(blank=True, default='', max_length=100)),
                ('custom_qr_url', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cooperating_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fundraisers', to='organizations.organization')),
            ],
        ),
    ]
