# Generated by Django 5.2.17 on 2026-08-30 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'CareLink Super Admin'), ('PLATFORM_ADMIN', 'CareLink Platform Admin'), ('ORGANIZATION_OWNER', 'Hospital / Organization Owner'), ('ORG_ADMIN', 'Hospital / Organization Admin'), ('MODERATOR', 'Healthcare Content Moderator'), ('DOCTOR', 'Doctor / Specialist'), ('NURSE', 'Community / Clinical Nurse'), ('VOLUNTEER', 'Volunteer'), ('RECEPTION', 'Reception & Desk Staff'), ('PHARMACIST', 'Pharmacist'), ('ACCOUNTANT', 'Accountant'), ('AMBULANCE_DRIVER', 'Ambulance Driver'), ('PATIENT', 'Patient'), ('FAMILY_MEMBER', 'Family Member'), ('BLOOD_DONOR', 'Blood Donor')], default='NURSE', max_length=50),
        ),
    ]
