# Generated by Django 5.2.17 on 2026-08-06 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id_code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('blood_group', models.CharField(max_length=10)),
                ('district', models.CharField(max_length=100)),
                ('ward', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('category_tier', models.CharField(choices=[('Category A (Bedridden)', 'Category A (Bedridden)'), ('Category B (Semi-mobile)', 'Category B (Semi-mobile)'), ('Category C (Mobile/Chronic)', 'Category C (Mobile/Chronic)'), ('Category D (Supportive)', 'Category D (Supportive)')], default='Category A (Bedridden)', max_length=100)),
                ('diagnosis', models.TextField()),
                ('risk_level', models.CharField(choices=[('High Risk', 'High Risk'), ('Moderate Risk', 'Moderate Risk'), ('Low Risk', 'Low Risk')], default='Moderate Risk', max_length=50)),
                ('ai_summary', models.TextField(blank=True, default='')),
                ('emergency_contact_name', models.CharField(max_length=100)),
                ('emergency_contact_phone', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyMemberContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('relation', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentIssued',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_name', models.CharField(max_length=200)),
                ('serial_number', models.CharField(max_length=100)),
                ('issued_date', models.DateField()),
                ('status', models.CharField(default='Active', max_length=50)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_issued', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='VitalsReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bp', models.CharField(max_length=20)),
                ('pulse', models.IntegerField()),
                ('spo2', models.IntegerField()),
                ('pain_scale', models.IntegerField()),
                ('recorded_by', models.CharField(max_length=100)),
                ('recorded_date', models.DateField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals_history', to='patients.patient')),
            ],
        ),
    ]
