# Generated by Django 5.2.17 on 2026-08-25 17:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patientauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='lifecycle_status',
            field=models.CharField(choices=[('Registration', 'Registration'), ('Assessment', 'Assessment'), ('Care Category', 'Care Category'), ('Care Plan', 'Care Plan'), ('Active Care', 'Active Care'), ('Follow-up', 'Follow-up'), ('Discharged', 'Discharged'), ('Archived', 'Archived')], default='Active Care', max_length=50),
        ),
        migrations.AddField(
            model_name='vitalsreading',
            name='recorded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='vitalsreading',
            name='respiratory_rate',
            field=models.IntegerField(default=16),
        ),
        migrations.AddField(
            model_name='vitalsreading',
            name='temperature',
            field=models.DecimalField(decimal_places=1, default=98.6, max_digits=4),
        ),
        migrations.AlterField(
            model_name='vitalsreading',
            name='pain_scale',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CarePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_nurse_name', models.CharField(max_length=100)),
                ('assigned_doctor_name', models.CharField(max_length=100)),
                ('care_goals', models.TextField(default='Pain management, wound dressing, and routine vitals monitoring.')),
                ('dietary_instructions', models.TextField(blank=True, default='')),
                ('emergency_escalation_notes', models.TextField(blank=True, default='')),
                ('review_frequency_days', models.IntegerField(default=14)),
                ('last_reviewed_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='care_plan', to='patients.patient')),
            ],
        ),
    ]
