# Generated by Django 5.2.17 on 2026-08-31 20:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_organization_status'),
        ('patients', '0003_patient_lifecycle_status_vitalsreading_recorded_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='careplan',
            name='dnr_or_advanced_directives',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='careplan',
            name='mobility_status',
            field=models.CharField(default='Bedridden (Category A)', max_length=100),
        ),
        migrations.AddField(
            model_name='careplan',
            name='pain_assessment_protocol',
            field=models.TextField(blank=True, default='WHO 3-step analgesic ladder, monitor every visit.'),
        ),
        migrations.AddField(
            model_name='careplan',
            name='psychological_support_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='careplan',
            name='visit_frequency',
            field=models.CharField(default='Weekly', max_length=50),
        ),
        migrations.AddField(
            model_name='vitalsreading',
            name='blood_sugar',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CaregiverAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caregiver_name', models.CharField(max_length=150)),
                ('caregiver_phone', models.CharField(max_length=20)),
                ('relationship', models.CharField(default='Family Member', max_length=100)),
                ('permissions', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('granted_by', models.CharField(default='Hospital Desk', max_length=150)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caregiver_grants', to='patients.patient')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caregiver_grants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CareTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('area_coverage', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_care_teams', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_teams', to='organizations.organization')),
                ('primary_nurse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_care_teams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='careplan',
            name='care_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_care_plans', to='patients.careteam'),
        ),
        migrations.CreateModel(
            name='MedicationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=200)),
                ('dosage', models.CharField(max_length=100)),
                ('route', models.CharField(default='Oral', max_length=50)),
                ('frequency', models.CharField(default='Twice Daily (Morning, Night)', max_length=100)),
                ('time_slots', models.JSONField(default=list)),
                ('prescribed_by_doctor', models.CharField(max_length=150)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('instructions', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_plans', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='MedicationAdministration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('time_slot', models.CharField(default='MORNING', max_length=30)),
                ('status', models.CharField(choices=[('TAKEN', 'Taken'), ('SKIPPED', 'Skipped'), ('MISSED', 'Missed'), ('REFUSED', 'Refused')], default='TAKEN', max_length=20)),
                ('recorded_by_caregiver', models.BooleanField(default=False)),
                ('verified_by_nurse', models.BooleanField(default=False)),
                ('verified_nurse_name', models.CharField(blank=True, default='', max_length=150)),
                ('administered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, default='')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_logs', to='patients.patient')),
                ('medication_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrations', to='patients.medicationplan')),
            ],
        ),
        migrations.CreateModel(
            name='PatientCareGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='Pain Management', max_length=100)),
                ('description', models.TextField()),
                ('target_date', models.DateField(blank=True, null=True)),
                ('is_achieved', models.BooleanField(default=False)),
                ('achieved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_goals', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='CareTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=150)),
                ('role', models.CharField(choices=[('DOCTOR', 'Consulting Doctor'), ('NURSE', 'Palliative / Community Nurse'), ('COMMUNITY_WORKER', 'Community Healthcare Worker'), ('PHYSIOTHERAPIST', 'Physiotherapist'), ('COUNSELOR', 'Psychological Counselor'), ('VOLUNTEER', 'Volunteer')], default='NURSE', max_length=40)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('care_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='patients.careteam')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='care_team_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('care_team', 'user')},
            },
        ),
    ]
