# Generated by Django 5.2.17 on 2026-08-06 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodDonor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('blood_group', models.CharField(max_length=10)),
                ('district', models.CharField(max_length=100)),
                ('locality', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('last_donation_date', models.DateField()),
                ('total_donations', models.IntegerField(default=1)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_donors', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=200)),
                ('blood_group', models.CharField(max_length=10)),
                ('hospital_name', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=100)),
                ('units_needed', models.IntegerField(default=1)),
                ('urgency', models.CharField(default='Emergency', max_length=50)),
                ('requested_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_requests', to='organizations.organization')),
            ],
        ),
    ]
