# Generated by Django 5.2.17 on 2026-08-25 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_donors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='fulfilled_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='responding_donor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responded_requests', to='blood_donors.blooddonor'),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('Matching', 'Matching'), ('Donors Notified', 'Donors Notified'), ('Donor Responded', 'Donor Responded'), ('Fulfilled', 'Fulfilled'), ('Closed', 'Closed')], default='Created', max_length=50),
        ),
    ]
