# Generated by Django 5.2.17 on 2026-08-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homevisit',
            name='assessment_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='homevisit',
            name='care_provided',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='homevisit',
            name='doctor_review_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='homevisit',
            name='doctor_signed_off',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='homevisit',
            name='doctor_signoff_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homevisit',
            name='equipment_used',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='homevisit',
            name='follow_up_instructions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='homevisit',
            name='medication_administered',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='homevisit',
            name='next_visit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homevisit',
            name='symptoms_observed',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='homevisit',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Assigned', 'Assigned'), ('Accepted', 'Accepted'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Doctor Review', 'Doctor Review'), ('Closed', 'Closed')], default='Scheduled', max_length=50),
        ),
    ]
