# Generated by Django 5.2.17 on 2026-08-31 20:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_organization_status'),
        ('patients', '0004_careplan_dnr_or_advanced_directives_and_more'),
        ('visits', '0002_homevisit_assessment_notes_homevisit_care_provided_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='homevisit',
            name='arrival_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homevisit',
            name='assigned_doctor_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='homevisit',
            name='care_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='patients.careteam'),
        ),
        migrations.AddField(
            model_name='homevisit',
            name='completion_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homevisit',
            name='dispatch_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homevisit',
            name='urgency',
            field=models.CharField(choices=[('ROUTINE', 'Routine'), ('PRIORITY', 'Priority (Palliative Tier B)'), ('URGENT', 'Urgent / Same-Day'), ('CRITICAL', 'Critical Emergency')], default='ROUTINE', max_length=30),
        ),
        migrations.AddField(
            model_name='homevisit',
            name='visit_type',
            field=models.CharField(choices=[('ROUTINE_PALLIATIVE', 'Routine Palliative Follow-up'), ('EMERGENCY_FOLLOWUP', 'Emergency Acute Follow-up'), ('CATHETER_CARE', 'Catheter / Stoma Care'), ('WOUND_DRESSING', 'Wound / Bedsore Dressing'), ('PAIN_MANAGEMENT', 'Severe Pain Assessment & Analgesic Review'), ('PHYSIOTHERAPY', 'Physiotherapy & Mobility Session'), ('COUNSELING', 'Psychological & Bereavement Counseling'), ('EQUIPMENT_DELIVERY', 'Equipment Delivery & Setup')], default='ROUTINE_PALLIATIVE', max_length=50),
        ),
        migrations.AddField(
            model_name='homevisit',
            name='vitals_reading',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_visit', to='patients.vitalsreading'),
        ),
        migrations.AlterField(
            model_name='homevisit',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Requested by Patient / Family'), ('ACCEPTED', 'Accepted by Hospital / Center'), ('REJECTED', 'Rejected'), ('TEAM_ASSIGNED', 'Care Team Assigned'), ('SCHEDULED', 'Scheduled'), ('TEAM_DISPATCHED', 'Team Dispatched / In Transit'), ('ARRIVED', 'Arrived at Patient Home'), ('IN_PROGRESS', 'Visit In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('RESCHEDULED', 'Rescheduled'), ('Assigned', 'Assigned'), ('Doctor Review', 'Doctor Review'), ('Closed', 'Closed')], default='SCHEDULED', max_length=50),
        ),
        migrations.CreateModel(
            name='CareTeamRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_date', models.DateField(default=django.utils.timezone.now)),
                ('primary_nurse_name', models.CharField(max_length=150)),
                ('status', models.CharField(default='PLANNED', max_length=30)),
                ('total_stops', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('care_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='patients.careteam')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_routes', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='HomeVisitRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_name', models.CharField(max_length=150)),
                ('requester_phone', models.CharField(max_length=20)),
                ('requester_relationship', models.CharField(default='Self / Family Member', max_length=100)),
                ('visit_type', models.CharField(choices=[('ROUTINE_PALLIATIVE', 'Routine Palliative Follow-up'), ('EMERGENCY_FOLLOWUP', 'Emergency Acute Follow-up'), ('CATHETER_CARE', 'Catheter / Stoma Care'), ('WOUND_DRESSING', 'Wound / Bedsore Dressing'), ('PAIN_MANAGEMENT', 'Severe Pain Assessment & Analgesic Review'), ('PHYSIOTHERAPY', 'Physiotherapy & Mobility Session'), ('COUNSELING', 'Psychological & Bereavement Counseling'), ('EQUIPMENT_DELIVERY', 'Equipment Delivery & Setup')], default='ROUTINE_PALLIATIVE', max_length=50)),
                ('urgency', models.CharField(choices=[('ROUTINE', 'Routine'), ('PRIORITY', 'Priority (Palliative Tier B)'), ('URGENT', 'Urgent / Same-Day'), ('CRITICAL', 'Critical Emergency')], default='ROUTINE', max_length=30)),
                ('preferred_date', models.DateField()),
                ('preferred_time_slot', models.CharField(default='10:00 AM - 12:00 PM', max_length=50)),
                ('reason_and_symptoms', models.TextField()),
                ('location_address', models.TextField()),
                ('status', models.CharField(default='PENDING', max_length=30)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_visit_requests', to='organizations.organization')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_requests', to='patients.patient')),
                ('requested_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_visit_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='homevisit',
            name='visit_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_visit', to='visits.homevisitrequest'),
        ),
        migrations.CreateModel(
            name='HomeVisitStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(max_length=50)),
                ('to_status', models.CharField(max_length=50)),
                ('changed_by_username', models.CharField(default='system', max_length=150)),
                ('notes', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='visits.homevisit')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_order', models.IntegerField(default=1)),
                ('location_area', models.CharField(max_length=150)),
                ('estimated_arrival_time', models.CharField(default='10:00 AM', max_length=50)),
                ('is_completed', models.BooleanField(default=False)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='visits.careteamroute')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_stop', to='visits.homevisit')),
            ],
            options={
                'ordering': ['sequence_order'],
            },
        ),
    ]
