# Generated by Django 5.2.17 on 2026-08-30 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_appointmentrequest_idempotency_key_and_more'),
        ('organizations', '0003_organization_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='healthcareprofile',
            options={'ordering': ['-profile_completeness_score', 'id']},
        ),
        migrations.AddField(
            model_name='healthcareprofile',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthcareprofile',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='healthcareprofile',
            name='lifecycle_status',
            field=models.CharField(choices=[('PROSPECT', 'Prospect Under Discovery'), ('INVITED', 'Invited (Pending Admin Activation)'), ('ACTIVATED', 'Activated (Account Setup Complete)'), ('PROFILE_INCOMPLETE', 'Profile Setup Incomplete'), ('SUBMITTED_FOR_REVIEW', 'Submitted for CareLink Review'), ('UNDER_REVIEW', 'Under CareLink Audit Review'), ('ACTION_REQUIRED', 'Action Required (Changes Requested)'), ('APPROVED', 'Approved by CareLink'), ('PUBLISHED', 'Published to Public Directory'), ('SUSPENDED', 'Suspended')], default='INVITED', max_length=40),
        ),
        migrations.AddField(
            model_name='healthcareprofile',
            name='profile_completeness_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='healthcareprofile',
            name='review_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='healthcareprofile',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='HealthcareProspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=100)),
                ('organization_type', models.CharField(choices=[('HOSPITAL', 'Multispecialty / General Hospital'), ('CLINIC', 'Medical Clinic / Polyclinic'), ('PALLIATIVE_CARE_CENTER', 'Palliative Care Center & Hospice'), ('NURSING_HOME', 'Nursing Home'), ('REHABILITATION_CENTER', 'Rehabilitation Center'), ('DIAGNOSTIC_CENTER', 'Diagnostic Center & Imaging Lab'), ('PHARMACY', 'Community Pharmacy'), ('BLOOD_BANK', 'Blood Bank & Component Center'), ('HOME_CARE_PROVIDER', 'Home Healthcare Provider'), ('OTHER', 'Other Healthcare Facility')], default='HOSPITAL', max_length=50)),
                ('ownership_type', models.CharField(choices=[('GOVERNMENT', 'Government / Public Sector (DHS / DME)'), ('PRIVATE', 'Private Healthcare'), ('TRUST', 'Charitable Trust / Non-Profit'), ('MISSION', 'Mission Hospital'), ('COOPERATIVE', 'Cooperative Society'), ('OTHER', 'Other Ownership')], default='PRIVATE', max_length=50)),
                ('contact_person', models.CharField(max_length=150)),
                ('contact_designation', models.CharField(default='Medical Director / Superintendent', max_length=150)),
                ('contact_phone', models.CharField(max_length=20)),
                ('contact_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('CONTACT_NOT_STARTED', 'Contact Not Started'), ('CONTACTED', 'Contacted'), ('INTERESTED', 'Interested in CareLink Network'), ('INVITED', 'Invitation Issued'), ('ACTIVATED', 'Admin Activated'), ('PROFILE_COMPLETED', 'Profile Completed'), ('VERIFIED', 'Verified & Published'), ('DECLINED', 'Declined')], default='CONTACT_NOT_STARTED', max_length=40)),
                ('internal_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_prospects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HospitalTeamInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=150)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('recipient_phone', models.CharField(blank=True, default='', max_length=20)),
                ('role', models.CharField(choices=[('ORGANIZATION_OWNER', 'Hospital / Organization Owner'), ('ORGANIZATION_ADMIN', 'Hospital Organization Administrator'), ('DEPARTMENT_MODERATOR', 'Departmental Content Moderator'), ('DOCTOR', 'Doctor / Specialist Consultant'), ('NURSE', 'Clinical / Palliative Nurse'), ('RECEPTION', 'Reception & Desk Staff'), ('PHARMACIST', 'Pharmacist'), ('STAFF', 'Healthcare Staff'), ('LIMITED_STAFF', 'Limited Staff Member')], default='STAFF', max_length=40)),
                ('designation', models.CharField(blank=True, default='', max_length=150)),
                ('token', models.CharField(db_index=True, max_length=128, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Activation'), ('ACCEPTED', 'Accepted & Activated'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked')], default='PENDING', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='network.department')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_team_invitations', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_invitations', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=150)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('recipient_phone', models.CharField(max_length=20)),
                ('recipient_designation', models.CharField(default='Authorized Hospital Administrator', max_length=150)),
                ('token', models.CharField(db_index=True, max_length=128, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Activation'), ('ACCEPTED', 'Accepted & Activated'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked')], default='PENDING', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_org_invitations', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='organizations.organization')),
                ('prospect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations', to='network.healthcareprospect')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ORGANIZATION_OWNER', 'Hospital / Organization Owner'), ('ORGANIZATION_ADMIN', 'Hospital Organization Administrator'), ('DEPARTMENT_MODERATOR', 'Departmental Content Moderator'), ('DOCTOR', 'Doctor / Specialist Consultant'), ('NURSE', 'Clinical / Palliative Nurse'), ('RECEPTION', 'Reception & Desk Staff'), ('PHARMACIST', 'Pharmacist'), ('STAFF', 'Healthcare Staff'), ('LIMITED_STAFF', 'Limited Staff Member')], default='STAFF', max_length=40)),
                ('status', models.CharField(choices=[('INVITED', 'Invited (Pending Acceptance)'), ('PENDING_APPROVAL', 'Pending Hospital Admin Approval'), ('ACTIVE', 'Active Member'), ('REJECTED', 'Membership Rejected'), ('SUSPENDED', 'Membership Suspended'), ('REVOKED', 'Membership Access Revoked')], default='PENDING_APPROVAL', max_length=30)),
                ('designation', models.CharField(blank=True, default='', max_length=150)),
                ('medical_registration_number', models.CharField(blank=True, default='', max_length=100)),
                ('permissions', models.JSONField(blank=True, default=dict)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_memberships', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to='network.department')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_team_invitations', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'organization')},
            },
        ),
    ]
