# Generated by Django 5.2.17 on 2026-08-30 19:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_healthcareprofile_options_and_more'),
        ('organizations', '0003_organization_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentrequest',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Appointment Requested by Patient'), ('PENDING_HOSPITAL', 'Pending Hospital Acceptance'), ('ACCEPTED', 'Accepted by Hospital Desk'), ('CONFIRMED', 'Confirmed & Token Issued'), ('CHECKED_IN', 'Patient Arrived & Checked In'), ('IN_CONSULTATION', 'In Consultation with Doctor'), ('COMPLETED', 'Consultation Completed'), ('CANCELLED', 'Cancelled'), ('REJECTED', 'Rejected by Hospital'), ('NO_SHOW', 'Patient Did Not Arrive'), ('RESCHEDULED', 'Rescheduled')], default='REQUESTED', max_length=30),
        ),
        migrations.CreateModel(
            name='AppointmentStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(max_length=30)),
                ('to_status', models.CharField(max_length=30)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='network.appointmentrequest')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='QueueSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField(default=django.utils.timezone.now)),
                ('room_number', models.CharField(default='OPD Room 102', max_length=50)),
                ('current_token_number', models.IntegerField(default=0)),
                ('total_tokens_issued', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_sessions', to='network.department')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_sessions', to='network.doctor')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_sessions', to='organizations.organization')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='network.doctorschedule')),
            ],
            options={
                'ordering': ['-session_date', '-started_at'],
            },
        ),
        migrations.CreateModel(
            name='DoctorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available on Duty'), ('ON_LEAVE', 'On Leave'), ('HOLIDAY', 'Hospital / Public Holiday'), ('EMERGENCY_DUTY', 'Emergency Casualty Duty'), ('UNAVAILABLE', 'Unavailable')], default='AVAILABLE', max_length=30)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='network.doctor')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_availabilities', to='organizations.organization')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('doctor', 'organization', 'date')},
            },
        ),
        migrations.CreateModel(
            name='QueueToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_number', models.IntegerField()),
                ('token_label', models.CharField(default='A-01', max_length=20)),
                ('patient_name', models.CharField(max_length=150)),
                ('patient_phone', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting in Queue'), ('CALLED', 'Called to OPD Room'), ('IN_CONSULTATION', 'In Consultation with Doctor'), ('COMPLETED', 'Consultation Completed'), ('SKIPPED', 'Skipped / On Hold'), ('CANCELLED', 'Cancelled / No Show')], default='WAITING', max_length=30)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('consultation_started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('clinical_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_tokens', to='network.appointmentrequest')),
                ('queue_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='network.queuesession')),
            ],
            options={
                'ordering': ['token_number'],
                'unique_together': {('queue_session', 'token_number')},
            },
        ),
        migrations.CreateModel(
            name='ScheduleException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exception_date', models.DateField()),
                ('is_cancelled', models.BooleanField(default=True)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('affiliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_exceptions', to='network.doctoraffiliation')),
                ('substitute_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substitute_duties', to='network.doctor')),
            ],
            options={
                'ordering': ['exception_date'],
                'unique_together': {('affiliation', 'exception_date')},
            },
        ),
    ]
