# Generated by Django 5.2.17 on 2026-08-31 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_appointmentrequest_status_and_more'),
        ('organizations', '0003_organization_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentrequest',
            name='cancellation_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='appointmentrequest',
            name='is_doctor_unavailable_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointmentrequest',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='appointmentrequest',
            name='reschedule_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='appointmentrequest',
            name='rescheduled_from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointmentrequest',
            name='rescheduled_from_slot',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='appointmentrequest',
            name='substitute_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substituted_appointments', to='network.doctor'),
        ),
        migrations.CreateModel(
            name='DomainEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=60)),
                ('entity_type', models.CharField(db_index=True, max_length=50)),
                ('entity_id', models.IntegerField(db_index=True)),
                ('actor_id', models.IntegerField(blank=True, null=True)),
                ('actor_username', models.CharField(default='system', max_length=150)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True, default='')),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domain_events', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
