# Generated by Django 5.2.17 on 2026-08-31 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_appointmentrequest_cancellation_reason_and_more'),
        ('organizations', '0003_organization_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='queuetoken',
            options={'ordering': ['-priority_rank', 'token_number']},
        ),
        migrations.AddField(
            model_name='queuesession',
            name='avg_consultation_duration_seconds',
            field=models.IntegerField(default=900),
        ),
        migrations.AddField(
            model_name='queuesession',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='queuesession',
            name='pause_reason',
            field=models.CharField(blank=True, choices=[('EMERGENCY', 'Emergency Surgery / Trauma Resuscitation'), ('DOCTOR_UNAVAILABLE', 'Doctor Briefly Unavailable / Ward Rounds'), ('BREAK', 'Scheduled Break / Lunch'), ('TECHNICAL', 'Technical / System Maintenance'), ('OTHER', 'Other Administrative Reason')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='queuesession',
            name='queue_type',
            field=models.CharField(choices=[('OPD', 'General OPD Consultation'), ('EMERGENCY', 'Emergency Casualty'), ('LABORATORY', 'Clinical Diagnostic Laboratory'), ('PHARMACY', 'Hospital Dispensary & Pharmacy'), ('RADIOLOGY', 'Radiology, X-Ray & Imaging'), ('REGISTRATION', 'Patient Intake & Registration'), ('BILLING', 'Billing & Insurance Desk'), ('PALLIATIVE', 'Palliative & Pain Triage')], default='OPD', max_length=30),
        ),
        migrations.AddField(
            model_name='queuesession',
            name='token_prefix',
            field=models.CharField(default='C', max_length=10),
        ),
        migrations.AddField(
            model_name='queuesession',
            name='total_completed_consultations',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='queuetoken',
            name='call_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='queuetoken',
            name='check_in_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='queuetoken',
            name='consultation_duration_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='queuetoken',
            name='is_walk_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='queuetoken',
            name='last_called_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='queuetoken',
            name='priority',
            field=models.CharField(choices=[('NORMAL', 'Normal Priority'), ('PRIORITY', 'Clinical Priority / Senior / Palliative Care Plan'), ('URGENT', 'Urgent / High Pain Triage'), ('EMERGENCY', 'Clinical Emergency (Immediate)')], default='NORMAL', max_length=30),
        ),
        migrations.AddField(
            model_name='queuetoken',
            name='priority_rank',
            field=models.IntegerField(default=1, help_text='1: Normal, 2: Priority, 3: Urgent, 4: Emergency'),
        ),
        migrations.AddField(
            model_name='queuetoken',
            name='qr_code_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='queuetoken',
            name='wait_time_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='queuetoken',
            name='token_label',
            field=models.CharField(default='C-01', max_length=20),
        ),
        migrations.CreateModel(
            name='PatientCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_method', models.CharField(default='QR_SCAN', max_length=30)),
                ('qr_payload', models.CharField(blank=True, default='', max_length=128)),
                ('checked_in_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkins', to='network.appointmentrequest')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_checkins', to='organizations.organization')),
                ('token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkins', to='network.queuetoken')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-checked_in_at'],
            },
        ),
        migrations.CreateModel(
            name='QueuePause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('EMERGENCY', 'Emergency Surgery / Trauma Resuscitation'), ('DOCTOR_UNAVAILABLE', 'Doctor Briefly Unavailable / Ward Rounds'), ('BREAK', 'Scheduled Break / Lunch'), ('TECHNICAL', 'Technical / System Maintenance'), ('OTHER', 'Other Administrative Reason')], max_length=30)),
                ('notes', models.TextField(blank=True, default='')),
                ('paused_at', models.DateTimeField(auto_now_add=True)),
                ('resumed_at', models.DateTimeField(blank=True, null=True)),
                ('paused_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('queue_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pauses', to='network.queuesession')),
            ],
            options={
                'ordering': ['-paused_at'],
            },
        ),
        migrations.CreateModel(
            name='WaitingTimeSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_time', models.DateTimeField(auto_now_add=True)),
                ('waiting_patients_count', models.IntegerField(default=0)),
                ('avg_wait_time_minutes', models.IntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wait_time_snapshots', to='organizations.organization')),
                ('queue_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wait_time_snapshots', to='network.queuesession')),
            ],
            options={
                'ordering': ['-snapshot_time'],
            },
        ),
        migrations.CreateModel(
            name='QueuePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_type', models.CharField(choices=[('OPD', 'General OPD Consultation'), ('EMERGENCY', 'Emergency Casualty'), ('LABORATORY', 'Clinical Diagnostic Laboratory'), ('PHARMACY', 'Hospital Dispensary & Pharmacy'), ('RADIOLOGY', 'Radiology, X-Ray & Imaging'), ('REGISTRATION', 'Patient Intake & Registration'), ('BILLING', 'Billing & Insurance Desk'), ('PALLIATIVE', 'Palliative & Pain Triage')], default='OPD', max_length=30)),
                ('default_avg_consultation_minutes', models.IntegerField(default=15)),
                ('max_recall_attempts', models.IntegerField(default=3)),
                ('recall_wait_seconds', models.IntegerField(default=120)),
                ('auto_no_show_after_recalls', models.BooleanField(default=True)),
                ('allow_digital_check_in', models.BooleanField(default=True)),
                ('check_in_window_hours_before', models.DecimalField(decimal_places=2, default=2.0, max_digits=4)),
                ('token_prefix', models.CharField(default='C', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_policies', to='organizations.organization')),
            ],
            options={
                'ordering': ['organization', 'queue_type'],
                'unique_together': {('organization', 'queue_type')},
            },
        ),
    ]
