# Generated by Django 5.2.17 on 2026-08-30 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_bank_account_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Application'), ('UNDER_REVIEW', 'Under Document Review'), ('ACTION_REQUIRED', 'Action Required'), ('ACTIVE', 'Active'), ('REJECTED', 'Application Rejected'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=30),
        ),
    ]
